// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Keyboard2 = lv_keyboard_create(ui_Screen3);
lv_obj_set_width( ui_Keyboard2, 232);
lv_obj_set_height( ui_Keyboard2, 120);
lv_obj_set_x( ui_Keyboard2, 1 );
lv_obj_set_y( ui_Keyboard2, 64 );
lv_obj_set_align( ui_Keyboard2, LV_ALIGN_CENTER );

ui_TextArea1 = lv_textarea_create(ui_Screen3);
lv_obj_set_width( ui_TextArea1, 226);
lv_obj_set_height( ui_TextArea1, 55);
lv_obj_set_x( ui_TextArea1, -1 );
lv_obj_set_y( ui_TextArea1, -104 );
lv_obj_set_align( ui_TextArea1, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea1,"SSID");



ui_TextArea3 = lv_textarea_create(ui_Screen3);
lv_obj_set_width( ui_TextArea3, 221);
lv_obj_set_height( ui_TextArea3, 57);
lv_obj_set_x( ui_TextArea3, -2 );
lv_obj_set_y( ui_TextArea3, -38 );
lv_obj_set_align( ui_TextArea3, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea3,"PASSWORD");



lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}
