// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_TimeLabel;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3( lv_event_t * e);
extern lv_obj_t *ui_Screen3;
extern lv_obj_t *ui_Keyboard2;
void ui_event_TextArea1( lv_event_t * e);
extern lv_obj_t *ui_TextArea1;
void ui_event_TextArea3( lv_event_t * e);
extern lv_obj_t *ui_TextArea3;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_152883419);   // assets\菇子.png

LV_FONT_DECLARE( ui_font_Font1);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
